blank_issues_enabled: false
contact_links:
  - name: Submit a request
    url: https://support.regulaforensics.com/hc/requests/new?utm_source=github
    about: Submit any requests to Regula Support Team
